# coding: utf-8

"""
    LUSID API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Dict, List
from pydantic import BaseModel, Field, conlist, constr
from lusid.models.compliance_template_parameter import ComplianceTemplateParameter
from lusid.models.perpetual_property import PerpetualProperty

class ComplianceTemplateVariation(BaseModel):
    """
    ComplianceTemplateVariation
    """
    label: constr(strict=True, min_length=1) = Field(..., description="Label of a Compliance Template Variation")
    description: constr(strict=True, min_length=1) = Field(..., description="The description of the Compliance Template Variation")
    required_parameters: conlist(ComplianceTemplateParameter) = Field(..., alias="requiredParameters", description="A parameter required by a Compliance Template Variation")
    properties: Dict[str, PerpetualProperty] = Field(..., description="Properties associated with the Compliance Template Variation")
    __properties = ["label", "description", "requiredParameters", "properties"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ComplianceTemplateVariation:
        """Create an instance of ComplianceTemplateVariation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in required_parameters (list)
        _items = []
        if self.required_parameters:
            for _item in self.required_parameters:
                if _item:
                    _items.append(_item.to_dict())
            _dict['requiredParameters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in properties (dict)
        _field_dict = {}
        if self.properties:
            for _key in self.properties:
                if self.properties[_key]:
                    _field_dict[_key] = self.properties[_key].to_dict()
            _dict['properties'] = _field_dict
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ComplianceTemplateVariation:
        """Create an instance of ComplianceTemplateVariation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ComplianceTemplateVariation.parse_obj(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in ComplianceTemplateVariation) in the input: " + obj)

        _obj = ComplianceTemplateVariation.parse_obj({
            "label": obj.get("label"),
            "description": obj.get("description"),
            "required_parameters": [ComplianceTemplateParameter.from_dict(_item) for _item in obj.get("requiredParameters")] if obj.get("requiredParameters") is not None else None,
            "properties": {k: (None if v is None else PerpetualProperty.from_dict(v)) for k, v in obj.get("properties").items()} if obj.get("properties") is not None else None,
        })
        return _obj

