# coding: utf-8

"""
    LUSID API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictBool, constr

class ComplianceTemplateParameter(BaseModel):
    """
    ComplianceTemplateParameter
    """
    name: constr(strict=True, min_length=1) = Field(..., description="The name for the required Compliance Template Parameter")
    description: constr(strict=True, min_length=1) = Field(..., description="The description for the required Compliance Template Parameter")
    type: constr(strict=True, min_length=1) = Field(..., description="The type for the required Compliance Template Parameter")
    is_checking_parameter: StrictBool = Field(..., alias="isCheckingParameter", description="Indicates whether this is the Compliance Template Parameter that will be used in the final check process")
    __properties = ["name", "description", "type", "isCheckingParameter"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ComplianceTemplateParameter:
        """Create an instance of ComplianceTemplateParameter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ComplianceTemplateParameter:
        """Create an instance of ComplianceTemplateParameter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ComplianceTemplateParameter.parse_obj(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in ComplianceTemplateParameter) in the input: " + obj)

        _obj = ComplianceTemplateParameter.parse_obj({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "type": obj.get("type"),
            "is_checking_parameter": obj.get("isCheckingParameter")
        })
        return _obj

